### ISSUE TITLE
Support for asymmetric algorithms such as RS256

### ISSUE THREAD

**Issue by nathandunn** [grails/grails-spring-security-core#1064]
I tried to change the get algorithm to RS256 to match the client.

```
    plugin:
        springsecurity:
            rest:
                token:
                    generation:
                        jwt:
                            algorithm: "RS256"
```

However, it JwtService only seems to return `HS256`.  Possibly a misconfiguration.
